/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/conversations` | `/conversations`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/wifi-setup` | `/wifi-setup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/conversation/[id]` | `/conversation/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(main)'}/device/[id]` | `/device/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(main)'}/onboarding/[deviceId]` | `/onboarding/[deviceId]`, params: Router.UnknownInputParams & { deviceId: string | number; } } | { pathname: `${'/(main)'}/profile/[deviceId]` | `/profile/[deviceId]`, params: Router.UnknownInputParams & { deviceId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/conversations` | `/conversations`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/discover` | `/discover`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/wifi-setup` | `/wifi-setup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/conversation/[id]` | `/conversation/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(main)'}/device/[id]` | `/device/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(main)'}/onboarding/[deviceId]` | `/onboarding/[deviceId]`, params: Router.UnknownOutputParams & { deviceId: string; } } | { pathname: `${'/(main)'}/profile/[deviceId]` | `/profile/[deviceId]`, params: Router.UnknownOutputParams & { deviceId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/conversations${`?${string}` | `#${string}` | ''}` | `/conversations${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/discover${`?${string}` | `#${string}` | ''}` | `/discover${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/wifi-setup${`?${string}` | `#${string}` | ''}` | `/wifi-setup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/conversations` | `/conversations`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/wifi-setup` | `/wifi-setup`; params?: Router.UnknownInputParams; } | `${'/(main)'}/conversation/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/conversation/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/device/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/device/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/onboarding/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/onboarding/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/profile/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(main)'}/conversation/[id]` | `/conversation/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(main)'}/device/[id]` | `/device/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(main)'}/onboarding/[deviceId]` | `/onboarding/[deviceId]`, params: Router.UnknownInputParams & { deviceId: string | number; } } | { pathname: `${'/(main)'}/profile/[deviceId]` | `/profile/[deviceId]`, params: Router.UnknownInputParams & { deviceId: string | number; } };
    }
  }
}
